# Generated by Django 5.0.6 on 2024-06-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='custom_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(default='Descripción por defecto', max_length=350),
        ),
    ]
