# Generated by Django 5.0.6 on 2024-07-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0003_alter_producto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='custom_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
